// constants.js
export const BASE_URL = 'https://scan-dine-backend-5qms.onrender.com' 
//export const BASE_URL = 'http://13.127.209.255:8080'
//export const BASE_URL = 'http://localhost:8080'
export const USER_URL = '/api/v1/user'
export const RESTAURANT_URL = '/api/v1/restaurant'
export const ORDER_URL = '/api/v1'
export const PAYPAL_URL = '/api/config/paypal'
export const MENU_URL = '/api/v1'
export const OFFER_URL = '/api/v1'
export const BOOK_TABLE_URL = '/api/v1/booking' 